# Generated by Django 4.0.3 on 2022-04-05 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=200)),
                ('phone', models.CharField(default='+46764064325f', max_length=20, validators=[django.core.validators.RegexValidator('^[/+]?[0-9 ]+$')])),
                ('email', models.EmailField(default='amab8901@gmail.com', max_length=200)),
                ('address', models.CharField(default='Johannesbäcksgatan 62F', max_length=200, validators=[django.core.validators.RegexValidator('^[a-öA-Ö0-9 ]+$')])),

                ('city', models.CharField(default='New York', max_length=200, validators=[django.core.validators.RegexValidator('^[a-öA-Ö ]+$')])),
                ('zip', models.CharField(default='', max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$')])),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='customer created')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpeg', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='browse.product'),
        ),
    ]
