# Generated by Django 4.0.3 on 2022-04-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_remove_product_price_product_stripe_product_id_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
    ]
