# Generated by Django 4.0.3 on 2022-04-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_product_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link',
            new_name='checkout_link',
        ),
    ]
