# Generated by Django 4.0.3 on 2022-04-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_rename_link_product_checkout_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='checkout_link',
            new_name='payment_link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_id',
        ),
    ]
